services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8090:8080"
  db:
    image: pgvector/pgvector:0.8.6-pg18-trixie
    container_name: pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: ihor
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data: